// Netlify build step: expose the PUBLIC Supabase settings to the browser.
// Only the URL and the anon key belong here — never the service-role key.
import { writeFileSync } from 'node:fs';

const env = {
  SUPABASE_URL: process.env.SUPABASE_URL || process.env.PUBLIC_SUPABASE_URL || '',
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || process.env.PUBLIC_SUPABASE_ANON_KEY || '',
  INTEGRATIONS_MODE: process.env.INTEGRATIONS_MODE || 'mock', // 'mock' shows a dev-integration banner
  SITE_URL: process.env.URL || '',
};
if (!env.SUPABASE_URL || !env.SUPABASE_ANON_KEY) {
  console.warn('[write-env] SUPABASE_URL / SUPABASE_ANON_KEY not set — the storefront will show a setup notice.');
}
writeFileSync(new URL('../public/js/lib/env.js', import.meta.url),
  `// Generated by scripts/write-env.mjs — do not edit or commit.\nexport const env = ${JSON.stringify(env, null, 2)};\n`);
console.log('[write-env] wrote public/js/lib/env.js');
